[[files]]
src = "keyd/default.conf"
dest = "/etc/keyd/default.conf"
mode = "0644"
owner = "root"
group = "root"
backup = true

[[files]]
type = "dir"
src = "portage"
dest = "/etc/portage"
only = ["gentoo"]
backup = true
